  site: 种植牙配件
  title: 种植牙配件
  description: >-
    登腾奥齿泰诺贝尔ITI仕诺康DIO百康ICX美格真INNO雅定等等

  # family=Noto+Sans+TC:wght@100;300&family=Noto+Sans:wght@100;200;300;400;500&family=Noto+Serif+SC:wght@300;400;500&family=Noto+Serif:wght@400;700&family=Play:wght@400;700
  # Fira+Code:wght@400;500;700 
  googlewebfonts: Noto+Serif+SC:wght@200;300;400;500;700
  lang: zh-CN
  timezone: Asia/Shanghai
  repo: https://aihi.one # site repo [optional]
  data-theme: dark # default theme "dark" | "light"

  author:
  name: 种植牙配件
  bio: 登腾奥齿泰诺贝尔ITI仕诺康DIO百康ICX美格真INNO雅定等等
  userpicture: 
  username: 武汉同学 # general username
  github:  # github username
  twitter:  # twitter username
  email: 

# URL settings
url: "https://aihi.one" #
baseurl: # leave blank if not wishd
permalink: "https://aihi.one"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->", "<!---", "--->"]
  ignore:
    envs: all

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
